# Generated by Django 4.2.11 on 2026-04-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_description_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'slug')},
        ),
    ]
