# Generated by Django 4.2.11 on 2026-04-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_options_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=350, help_text='Calories per 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, default=70.0, help_text='Carbohydrates in grams per 100g', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Fat in grams per 100g', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.DecimalField(decimal_places=1, default=12.0, help_text='Fiber in grams per 100g', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='iron',
            field=models.DecimalField(decimal_places=1, default=8.0, help_text='Iron percentage per 100g', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=12.0, help_text='Protein in grams per 100g', max_digits=5),
        ),
    ]
